Fix an issue when git-check finds error and it terminates the entire workflow

diff --git a/.github/workflows/updatelist.yaml b/.github/workflows/updatelist.yaml
--- a/.github/workflows/updatelist.yaml
+++ b/.github/workflows/updatelist.yaml
@@ -21,7 +21,7 @@ jobs:
       - name: Check for changes
         id: git-check
         run: |
-          git diff --exit-code
+          git diff --exit-code || true # Ignore the exit code
           echo "::set-output name=has_changes::$?"
 
       - name: Check for existing PR
